FROM alpine:3.15.0
LABEL maintainer="HAMZA Assoumani" os="alpine" distro="Alpine 3.15.0"
ENV CONTAINER_USER="hamza"
RUN adduser $CONTAINER_USER --disabled-password
CMD echo "hello-alpine, I'm Mr. Hamza and this is a container from my first image"
