FROM alpine:3.15.0
LABEL maintainer="HAMZA Assoumani" os="alpine" distro=""
ENV CONTAINER_USER="hamza"
RUN useradd $CONTAINER_USER
CMD echo "hello-alpine, I'm Mr. Hamza and this is a container from my first image"

